name: base
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - aiobotocore=1.4.0
  - coiled=0.0.53
  - cpuonly
  - dask=2021.8.1
  - dask-labextension=5.1.0
  - dask-ml=1.9.0
  - distributed=2021.8.1
  - h5py=3.3.0
  - imageio=2.9.0
  - ipywidgets=7.6.3
  - jupyterlab=3.1.12
  - matplotlib=3.4.3
  - numpy=1.21.2
  - onnxruntime=1.7.2
  - pandas=1.3.2
  - pip
  - pyarrow=5.0.0
  - python-graphviz=0.17
  - pytorch=1.9.0
  - s3fs=2021.8.0
  - scikit-learn=0.24.2
  - tpot=0.11.7
  - xgboost=1.4.0
  - zarr=2.8.3
  - pip:
    - nbmake==0.5
